/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.Gui;

import com.mycompany.model.Vehiculo;
import com.mycompany.servicios.ServicioVehiculo;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan Esteban Aponte
 */
public class GUIPrincipal extends javax.swing.JFrame {
    ServicioVehiculo vehiculo = new ServicioVehiculo();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIPrincipal.class.getName());

    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menuitemListarVehiculos = new javax.swing.JMenuItem();
        menuitemAgregarVehiculo = new javax.swing.JMenuItem();
        menuitemActualizar = new javax.swing.JMenuItem();
        menuBuscar = new javax.swing.JMenuItem();
        menuitemCambioEstado = new javax.swing.JMenuItem();
        menuSuma = new javax.swing.JMenuItem();
        menuACERCADE = new javax.swing.JMenu();
        menuCreadores = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CASA TORO");

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 2, 48)); // NOI18N
        jLabel1.setText("CASA TORO");

        jMenu1.setText("Archivo");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Vehiculo");

        menuitemListarVehiculos.setText("ListarVehiculo");
        menuitemListarVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemListarVehiculosActionPerformed(evt);
            }
        });
        jMenu2.add(menuitemListarVehiculos);

        menuitemAgregarVehiculo.setText("AgregarVehicula");
        menuitemAgregarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemAgregarVehiculoActionPerformed(evt);
            }
        });
        jMenu2.add(menuitemAgregarVehiculo);

        menuitemActualizar.setText("Actualizar");
        menuitemActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemActualizarActionPerformed(evt);
            }
        });
        jMenu2.add(menuitemActualizar);

        menuBuscar.setText("Buscar");
        menuBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBuscarActionPerformed(evt);
            }
        });
        jMenu2.add(menuBuscar);

        menuitemCambioEstado.setText("CambioEstado");
        menuitemCambioEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemCambioEstadoActionPerformed(evt);
            }
        });
        jMenu2.add(menuitemCambioEstado);

        menuSuma.setText("Suma de precios");
        menuSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSumaActionPerformed(evt);
            }
        });
        jMenu2.add(menuSuma);

        jMenuBar1.add(jMenu2);

        menuACERCADE.setText("Acerca de...");

        menuCreadores.setText("Creadores");
        menuCreadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCreadoresActionPerformed(evt);
            }
        });
        menuACERCADE.add(menuCreadores);

        jMenuBar1.add(menuACERCADE);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuitemListarVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemListarVehiculosActionPerformed
            GUIListarVehiculos gui = new GUIListarVehiculos();
        
        gui.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_menuitemListarVehiculosActionPerformed

    private void menuitemAgregarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemAgregarVehiculoActionPerformed
        GUIAgregarVehiculo gui = new GUIAgregarVehiculo();
        
        gui.setVisible(true);     // TODO add your handling code here:
    }//GEN-LAST:event_menuitemAgregarVehiculoActionPerformed

    private void menuitemActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemActualizarActionPerformed
        GUIActualizarVehiculo gui = new GUIActualizarVehiculo();
        gui.setVisible(true);

    }//GEN-LAST:event_menuitemActualizarActionPerformed

    private void menuitemCambioEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemCambioEstadoActionPerformed
        GUICambioEstado gui = new GUICambioEstado();
        gui.setVisible(true);

    }//GEN-LAST:event_menuitemCambioEstadoActionPerformed

    private void menuSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSumaActionPerformed
        GUISumaPrecios gui = new GUISumaPrecios();
        gui.setVisible(true);
                

    }//GEN-LAST:event_menuSumaActionPerformed

    private void menuBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBuscarActionPerformed
     GUIBuscar gui = new GUIBuscar();
     gui.setVisible(true);
    }//GEN-LAST:event_menuBuscarActionPerformed

    private void menuCreadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCreadoresActionPerformed
        JOptionPane.showMessageDialog(this,"JUAN ESTEBAN APONTE RUIZ 2220241096\n"+"Juan Esteban Molano 2220232008\n"+"Nicolás Francisco Tovar Gonzalez 2220242028\n");

    }//GEN-LAST:event_menuCreadoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
            
        java.awt.EventQueue.invokeLater(() -> new GUIPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuACERCADE;
    private javax.swing.JMenuItem menuBuscar;
    private javax.swing.JMenuItem menuCreadores;
    private javax.swing.JMenuItem menuSuma;
    private javax.swing.JMenuItem menuitemActualizar;
    private javax.swing.JMenuItem menuitemAgregarVehiculo;
    private javax.swing.JMenuItem menuitemCambioEstado;
    private javax.swing.JMenuItem menuitemListarVehiculos;
    // End of variables declaration//GEN-END:variables
}
